language: php

sudo: false

matrix:
  include:
    - php: 5.4
      env:
        - COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.1

before_script:
    - phpenv config-rm xdebug.ini
    - travis_wait 30 composer update $COMPOSER_FLAGS

script: bin/phpspec run -v -f pretty
